# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "batch-0.5.0" = {
      name = "batch";
      packageName = "batch";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/batch/-/batch-0.5.0.tgz";
        sha1 = "fd2e05a7a5d696b4db9314013e285d8ff3557ec3";
      };
    };
    "buffer-crc32-0.2.1" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz";
        sha1 = "be3e5382fc02b6d6324956ac1af98aa98b08534c";
      };
    };
    "bytes-0.2.1" = {
      name = "bytes";
      packageName = "bytes";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-0.2.1.tgz";
        sha1 = "555b08abcb063f8975905302523e4cd4ffdfdf31";
      };
    };
    "commander-1.3.2" = {
      name = "commander";
      packageName = "commander";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-1.3.2.tgz";
        sha1 = "8a8f30ec670a6fdd64af52f1914b907d79ead5b5";
      };
    };
    "commander-2.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.1.0.tgz";
        sha1 = "d121bbae860d9992a3d517ba96f56588e47c6781";
      };
    };
    "connect-2.12.0" = {
      name = "connect";
      packageName = "connect";
      version = "2.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-2.12.0.tgz";
        sha1 = "31d8fa0dcacdf1908d822bd2923be8a2d2a7ed9a";
      };
    };
    "cookie-0.1.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.0.tgz";
        sha1 = "90eb469ddce905c866de687efc43131d8801f9d0";
      };
    };
    "cookie-signature-1.0.1" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz";
        sha1 = "44e072148af01e6e8e24afbf12690d68ae698ecb";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "debug-0.7.4" = {
      name = "debug";
      packageName = "debug";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-0.7.4.tgz";
        sha1 = "06e1ea8082c2cb14e39806e22e2f6f757f92af39";
      };
    };
    "duplexer-0.1.1" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.1.1.tgz";
        sha1 = "ace6ff808c1ce66b57d1ebf97977acb02334cfc1";
      };
    };
    "express-3.4.8" = {
      name = "express";
      packageName = "express";
      version = "3.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-3.4.8.tgz";
        sha1 = "aa7a8986de07053337f4bc5ed9a6453d9cc8e2e1";
      };
    };
    "fresh-0.2.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz";
        sha1 = "bfd9402cf3df12c4a4c310c79f99a3dde13d34a7";
      };
    };
    "hyperquest-0.2.0" = {
      name = "hyperquest";
      packageName = "hyperquest";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyperquest/-/hyperquest-0.2.0.tgz";
        sha1 = "4d3e59af6604e8ccab73f76896d5844495fa85aa";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "keypress-0.1.0" = {
      name = "keypress";
      packageName = "keypress";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz";
        sha1 = "4a3188d4291b66b4f65edb99f806aa9ae293592a";
      };
    };
    "merge-descriptors-0.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-0.0.1.tgz";
        sha1 = "2ff0980c924cf81d0b5d1fb601177cb8bb56c0d0";
      };
    };
    "methods-0.1.0" = {
      name = "methods";
      packageName = "methods";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-0.1.0.tgz";
        sha1 = "335d429eefd21b7bacf2e9c922a8d2bd14a30e4f";
      };
    };
    "mime-1.2.11" = {
      name = "mime";
      packageName = "mime";
      version = "1.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.2.11.tgz";
        sha1 = "58203eed86e3a5ef17aed2b7d9ebd47f0a60dd10";
      };
    };
    "mkdirp-0.3.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz";
        sha1 = "de3e5f8961c88c787ee1368df849ac4413eca8d7";
      };
    };
    "multiparty-2.2.0" = {
      name = "multiparty";
      packageName = "multiparty";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz";
        sha1 = "a567c2af000ad22dc8f2a653d91978ae1f5316f4";
      };
    };
    "negotiator-0.3.0" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.3.0.tgz";
        sha1 = "706d692efeddf574d57ea9fb1ab89a4fa7ee8f60";
      };
    };
    "pause-0.0.1" = {
      name = "pause";
      packageName = "pause";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pause/-/pause-0.0.1.tgz";
        sha1 = "1d408b3fdb76923b9543d96fb4c9dfd535d9cb5d";
      };
    };
    "qs-0.6.6" = {
      name = "qs";
      packageName = "qs";
      version = "0.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-0.6.6.tgz";
        sha1 = "6e015098ff51968b8a3c819001d5f2c89bc4b107";
      };
    };
    "range-parser-0.0.4" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz";
        sha1 = "c0427ffef51c10acba0782a46c9602e744ff620b";
      };
    };
    "raw-body-1.1.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-1.1.2.tgz";
        sha1 = "c74b3004dea5defd1696171106ac740ec31d62be";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "send-0.1.4" = {
      name = "send";
      packageName = "send";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.1.4.tgz";
        sha1 = "be70d8d1be01de61821af13780b50345a4f71abd";
      };
    };
    "stream-counter-0.2.0" = {
      name = "stream-counter";
      packageName = "stream-counter";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-counter/-/stream-counter-0.2.0.tgz";
        sha1 = "ded266556319c8b0e222812b9cf3b26fa7d947de";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "through-2.2.7" = {
      name = "through";
      packageName = "through";
      version = "2.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.2.7.tgz";
        sha1 = "6e8e21200191d4eb6a99f6f010df46aa1c6eb2bd";
      };
    };
    "uid2-0.0.3" = {
      name = "uid2";
      packageName = "uid2";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid2/-/uid2-0.0.3.tgz";
        sha1 = "483126e11774df2f71b8b639dcd799c376162b82";
      };
    };
    "win-fork-1.0.0" = {
      name = "win-fork";
      packageName = "win-fork";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/win-fork/-/win-fork-1.0.0.tgz";
        sha1 = "6f21f7ec3ee07152b1030c60861cde38e7b66646";
      };
    };
  };
  args = {
    name = "httpipe";
    packageName = "httpipe";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."batch-0.5.0"
      sources."buffer-crc32-0.2.1"
      sources."bytes-0.2.1"
      sources."commander-2.1.0"
      sources."connect-2.12.0"
      sources."cookie-0.1.0"
      sources."cookie-signature-1.0.1"
      sources."core-util-is-1.0.2"
      sources."debug-0.7.4"
      sources."duplexer-0.1.1"
      (sources."express-3.4.8" // {
        dependencies = [
          sources."commander-1.3.2"
        ];
      })
      sources."fresh-0.2.0"
      sources."hyperquest-0.2.0"
      sources."inherits-2.0.3"
      sources."isarray-0.0.1"
      sources."keypress-0.1.0"
      sources."merge-descriptors-0.0.1"
      sources."methods-0.1.0"
      sources."mime-1.2.11"
      sources."mkdirp-0.3.5"
      sources."multiparty-2.2.0"
      sources."negotiator-0.3.0"
      sources."pause-0.0.1"
      sources."qs-0.6.6"
      sources."range-parser-0.0.4"
      sources."raw-body-1.1.2"
      sources."readable-stream-1.1.14"
      sources."send-0.1.4"
      sources."stream-counter-0.2.0"
      sources."string_decoder-0.10.31"
      sources."through-2.2.7"
      sources."uid2-0.0.3"
      sources."win-fork-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "pipe output to http and back";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}